### ISSUE TITLE
demo failed.

### ISSUE THREAD

**Issue by ictar** [aphistic/gomol#19]
I run the example but get "cannot use map[string]interface {} literal (type map[string]interface {}) as type *gomol.Attrs in argument to gomol.Dbgm". 

On the other hand, it seems the configuration for line number and  filename is not working. My code is as below:
```
	config := gomol.NewConfig()
	config.FilenameAttr = "filename"
	config.LineNumberAttr = "line"
	b := gomol.NewBase()
	b.SetConfig(config)

	// Add a console logger
	consoleCfg := gc.NewConsoleLoggerConfig()
	consoleLogger, _ := gc.NewConsoleLogger(consoleCfg)
	b.AddLogger(consoleLogger)

	// Set some global attrs that will be added to all
	// messages automatically
	b.SetAttr("another_name", "ele")

	// Initialize the loggers
	b.InitLoggers()
	defer b.ShutdownLoggers()

	// Log some debug messages with message-level attrs
	// that will be sent only with that message
	for i := 0; i < 10; i++ {
		b.Infom(gomol.NewAttrsFromMap(map[string]interface{}{"test": 1}),
			"msg string: %d", i)
	}
```
and the output is
```
[INFO] msg string: 0
[INFO] msg string: 1
[INFO] msg string: 2
[INFO] msg string: 3
[INFO] msg string: 4
[INFO] msg string: 5
[INFO] msg string: 6
[INFO] msg string: 7
[INFO] msg string: 8
[INFO] msg string: 9
```
no linenumber, no filename as well as attr I set.

**Comment by aphistic** [comment]
Hey! Sorry about that! I've pushed an updated version of the example in the README that fixes the build issue you ran into and hopefully clarifies your other question in regards to the line number and filename.  

By default the template used for the console logger doesn't print the attributes attached to the message because it can get pretty verbose in the console but it does include a couple other templates you can use by default. The one I've updated it to use is the one here: https://godoc.org/github.com/aphistic/gomol-console#NewTemplateFull

You can also write your own templates if the provided ones don't fit your needs using this: https://godoc.org/github.com/aphistic/gomol#Template

Hope this helps!

**Comment by ictar** [comment]
Yes, I can get the expected result. thx~
