### ISSUE TITLE
Log Level

### ISSUE THREAD

**Issue by efritz** [aphistic/gomol#4]
Can't filter!!

**Comment by efritz** [comment]
Can we have different log outputs have different log levels (GELF will log debug, but file will only log warnings or above)? I saw that this is attached to the Base object and not the logger itself, which is fine if you can make multiple base instances (is it natural / idiomatic to do so?).

If so, could you add a quick sample to the README?

**Comment by aphistic** [comment]
Yeah, I'm planning on having different levels for each logger but I wanted to get this done for you by tomorrow and I haven't been able to think of a good way to short-circuit the message early enough that it's not looping over all the loggers.  Maybe I'm worrying too much about that performance since it's all happening in a separate goroutine anyway?

I did originally have it so you could have multiple Base objects but it was causing problems with the flushing/shutdown stuff and I figured it was probably not going to be used enough to warrant the additional work.  I did keep it around just in case I need to re-add it in the future though.
